#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - step:
        name: Build and Unit Test
        script:
          - python3 --version
          - python3 -m venv env
          - source env/bin/activate
          - if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          - cd unittest
          - python3 -m unittest discover -p "*test*.py" -v