#  CI/CD Implementation

image: python:3.8

definitions:
  steps:
    - step: &build-and-unittest
        name: Build and Unit Test
        script:
          - python3 --version
          - python3 -m venv env
          - source env/bin/activate
          - if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          - cd unittest
          - python3 -m unittest discover -p "*test*.py" -v

pipelines:
  default:
    - step: *build-and-unittest

  branches:
    master:
      - step: *build-and-unittest

      - parallel:
        - step:
            name: Deploy to Demand Cloud
            script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: $USER
                  SERVER: $DEMAND_SERVER
                  MODE: "command"
                  COMMAND: "/home/team22/webhooks/team22-redeploy.sh ${BITBUCKET_REPO_SLUG}"

        - step:
            name: Deploy to Supply Cloud
            script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: $USER
                  SERVER: $SUPPLY_SERVER
                  MODE: "command"
                  COMMAND: "/home/team22/webhooks/team22-redeploy.sh ${BITBUCKET_REPO_SLUG}"

