#  CI/CD Implementation

image: python:3.8

definitions:
  services:
    mongo:
      image: mongo
  steps:
    - step: &build-and-unittest
        name: Build and Unit Test
        script:
          - wget https://repo.mongodb.org/apt/debian/dists/buster/mongodb-org/4.4/main/binary-amd64/mongodb-org-shell_4.4.5_amd64.deb && apt install ./mongodb-org-shell_4.4.5_amd64.deb
          - mongo --port 27017 --eval 'db.getSiblingDB("admin").createUser({ user:"admin", pwd:"'"$MONGO_ADMIN_PW"'", roles:[{role:"root", db:"admin"}]})'
          - mongo --port 27017 -u 'admin' -p $MONGO_ADMIN_PW --authenticationDatabase 'admin' --eval 'db.getSiblingDB("team22_demand").createUser({ user:"developer", pwd:"'"$MONGO_TEAM_PW"'", roles:["readWrite"]})'
          - mongo --port 27017 -u 'admin' -p $MONGO_ADMIN_PW --authenticationDatabase 'admin' --eval 'db.getSiblingDB("team22_supply").createUser({ user:"developer", pwd:"'"$MONGO_TEAM_PW"'", roles:["readWrite"]})'
          - echo 'MONGO_SECRET="'"$MONGO_TEAM_PW"'"' > .env
          - python3 --version
          - python3 -m venv env
          - source env/bin/activate
          - if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          - cd unittest
          - python3 -m unittest discover -p "*test*.py" -v
        services: 
          - mongo

pipelines:
  default:
    - step: *build-and-unittest

  branches:
    master:
      - step: *build-and-unittest

      - parallel:
        - step:
            name: Deploy to Demand Cloud
            script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: $USER
                  SERVER: $DEMAND_SERVER
                  MODE: "command"
                  COMMAND: "/home/team22/webhooks/team22-redeploy.sh ${BITBUCKET_REPO_SLUG}"

        - step:
            name: Deploy to Supply Cloud
            script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: $USER
                  SERVER: $SUPPLY_SERVER
                  MODE: "command"
                  COMMAND: "/home/team22/webhooks/team22-redeploy.sh ${BITBUCKET_REPO_SLUG}"

