#  CI/CD Implementation

image: python:3.8

definitions:
  caches:
    mongo: /usr/bin/
  services:
    mongo:
      image: mongo
  steps:
    - step: &build-and-unittest
        max-time: 1
        caches:
          - mongo
          - pip
        name: Build and Unit Test
        script:
          - if ! which mongo >/dev/null; then wget https://repo.mongodb.org/apt/debian/dists/buster/mongodb-org/4.4/main/binary-amd64/mongodb-org-shell_4.4.5_amd64.deb; apt install ./mongodb-org-shell_4.4.5_amd64.deb; fi
          - mongo --port 27017 --eval 'db.getSiblingDB("team22_demand").createUser({ user:"developer", pwd:"'"$MONGO_TEAM_PW"'", roles:["readWrite"]})'
          - mongo --port 27017 --eval 'db.getSiblingDB("team22_supply").createUser({ user:"developer", pwd:"'"$MONGO_TEAM_PW"'", roles:["readWrite"]})'
          - echo 'MONGO_SECRET="'"$MONGO_TEAM_PW"'"' > .env
          - if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          - cd unittest
          - python3 -m xmlrunner discover -p "*test*.py" -o ./test-reports/  
        services: 
          - mongo

pipelines:
  default:
    - step: *build-and-unittest

  branches:
    master:
      - step: *build-and-unittest

      - parallel:
        - step:
            name: Deploy to Demand Cloud Production
            deployment: production-demand
            clone:
              enabled: false
            script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: $USER
                  SERVER: $DEMAND_SERVER
                  MODE: "command"
                  COMMAND: "/home/team22/webhooks/team22-redeploy.sh ${BITBUCKET_REPO_SLUG} ${BITBUCKET_COMMIT} "

        - step:
            name: Deploy to Supply Cloud Production
            deployment: production-supply
            clone:
              enabled: false
            script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: $USER
                  SERVER: $SUPPLY_SERVER
                  MODE: "command"
                  COMMAND: "/home/team22/webhooks/team22-redeploy.sh ${BITBUCKET_REPO_SLUG} ${BITBUCKET_COMMIT}"

